### ISSUE TITLE
Is it suitable for multivariate time series with mixture of categorical and continuous features

### ISSUE THREAD

**Issue by Sandy4321** [cerlymarco/tspiral#2]
Is it suitable for multivariate time series with mixture of categorical and continuous features

**Comment by cerlymarco** [comment]
Hi,

Sure! Multivariate time series forecasting is natively supported. If the received scikit-learn model (`estimator`) doesn't support multivariate targets, use it in `MultiOutputRegressor`.

ALL the estimators in tspiral are sklearn estiamtors. They don't automatically encode categorical features. You should use your own strategy for categorical features encoding.
