### ISSUE TITLE
Name mismatch tspiral <--> tsprial

### ISSUE THREAD

**Issue by jorisparet** [cerlymarco/tspiral#3]
Hello,

I just started using your package and noticed a mismatch between the package name on PyPI and the README (`tspiral`) and the source package on the repository (`tsprial`). The install is done with

```
pip install tspiral
```

while the import is done with

```python
import tsprial
```

which is a bit perplexing. Perhaps this was done on purpose (in which case I apologize for raising this as an issue), but I thought that maybe you had not noticed.

Cheers.

**Comment by cerlymarco** [comment]
Hi, this is fixed in the new release (0.3.0) where global forecasting is natively introduced

`pip install --upgrade tspiral`
